"""empty message

Revision ID: 3bb1892fe9c8
Revises: e42269e59126
Create Date: 2022-06-30 09:46:19.418444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb1892fe9c8'
down_revision = 'e42269e59126'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missiles',
    sa.Column('system_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=50), nullable=True),
    sa.Column('system_country', sa.String(length=50), nullable=True),
    sa.Column('system_range_class', sa.String(length=15), nullable=True),
    sa.Column('system_warhead', sa.String(length=15), nullable=True),
    sa.Column('system_range', sa.String(length=15), nullable=True),
    sa.Column('system_nuke_type', sa.String(length=15), nullable=True),
    sa.Column('system_launcher', sa.String(length=15), nullable=True),
    sa.Column('system_description', sa.Text(), nullable=True),
    sa.Column('system_image', sa.String(length=50), nullable=True),
    sa.Column('system_type', sa.String(length=50), nullable=True),
    sa.Column('system_status', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('system_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missiles')
    op.drop_table('category')
    # ### end Alembic commands ###
