"""empty message

Revision ID: 8c7ed3d58f5b
Revises: 5ad774dedc88
Create Date: 2022-06-30 10:43:27.501534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7ed3d58f5b'
down_revision = '5ad774dedc88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
